// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Infoblox-CTO/atlas.feature.flag/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6544829dd69549ee, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type FeatureFlag struct {
	FeatureName          string   `protobuf:"bytes,1,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureFlag) Reset()         { *m = FeatureFlag{} }
func (m *FeatureFlag) String() string { return proto.CompactTextString(m) }
func (*FeatureFlag) ProtoMessage()    {}
func (*FeatureFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_6544829dd69549ee, []int{1}
}

func (m *FeatureFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureFlag.Unmarshal(m, b)
}
func (m *FeatureFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureFlag.Marshal(b, m, deterministic)
}
func (m *FeatureFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureFlag.Merge(m, src)
}
func (m *FeatureFlag) XXX_Size() int {
	return xxx_messageInfo_FeatureFlag.Size(m)
}
func (m *FeatureFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureFlag.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureFlag proto.InternalMessageInfo

func (m *FeatureFlag) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *FeatureFlag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *FeatureFlag) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type ListFeatureFlagRequest struct {
	Filter               *query.Filtering  `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListFeatureFlagRequest) Reset()         { *m = ListFeatureFlagRequest{} }
func (m *ListFeatureFlagRequest) String() string { return proto.CompactTextString(m) }
func (*ListFeatureFlagRequest) ProtoMessage()    {}
func (*ListFeatureFlagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6544829dd69549ee, []int{2}
}

func (m *ListFeatureFlagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeatureFlagRequest.Unmarshal(m, b)
}
func (m *ListFeatureFlagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeatureFlagRequest.Marshal(b, m, deterministic)
}
func (m *ListFeatureFlagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeatureFlagRequest.Merge(m, src)
}
func (m *ListFeatureFlagRequest) XXX_Size() int {
	return xxx_messageInfo_ListFeatureFlagRequest.Size(m)
}
func (m *ListFeatureFlagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeatureFlagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeatureFlagRequest proto.InternalMessageInfo

func (m *ListFeatureFlagRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListFeatureFlagRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ListFeatureFlagResponse struct {
	Results              []*FeatureFlag  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListFeatureFlagResponse) Reset()         { *m = ListFeatureFlagResponse{} }
func (m *ListFeatureFlagResponse) String() string { return proto.CompactTextString(m) }
func (*ListFeatureFlagResponse) ProtoMessage()    {}
func (*ListFeatureFlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6544829dd69549ee, []int{3}
}

func (m *ListFeatureFlagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeatureFlagResponse.Unmarshal(m, b)
}
func (m *ListFeatureFlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeatureFlagResponse.Marshal(b, m, deterministic)
}
func (m *ListFeatureFlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeatureFlagResponse.Merge(m, src)
}
func (m *ListFeatureFlagResponse) XXX_Size() int {
	return xxx_messageInfo_ListFeatureFlagResponse.Size(m)
}
func (m *ListFeatureFlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeatureFlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeatureFlagResponse proto.InternalMessageInfo

func (m *ListFeatureFlagResponse) GetResults() []*FeatureFlag {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListFeatureFlagResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

type ReadFeatureFlagRequest struct {
	FeatureName          string                `protobuf:"bytes,1,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	Labels               map[string]string     `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadFeatureFlagRequest) Reset()         { *m = ReadFeatureFlagRequest{} }
func (m *ReadFeatureFlagRequest) String() string { return proto.CompactTextString(m) }
func (*ReadFeatureFlagRequest) ProtoMessage()    {}
func (*ReadFeatureFlagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6544829dd69549ee, []int{4}
}

func (m *ReadFeatureFlagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadFeatureFlagRequest.Unmarshal(m, b)
}
func (m *ReadFeatureFlagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadFeatureFlagRequest.Marshal(b, m, deterministic)
}
func (m *ReadFeatureFlagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadFeatureFlagRequest.Merge(m, src)
}
func (m *ReadFeatureFlagRequest) XXX_Size() int {
	return xxx_messageInfo_ReadFeatureFlagRequest.Size(m)
}
func (m *ReadFeatureFlagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadFeatureFlagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadFeatureFlagRequest proto.InternalMessageInfo

func (m *ReadFeatureFlagRequest) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *ReadFeatureFlagRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ReadFeatureFlagRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ReadFeatureFlagResponse struct {
	Result               *FeatureFlag `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadFeatureFlagResponse) Reset()         { *m = ReadFeatureFlagResponse{} }
func (m *ReadFeatureFlagResponse) String() string { return proto.CompactTextString(m) }
func (*ReadFeatureFlagResponse) ProtoMessage()    {}
func (*ReadFeatureFlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6544829dd69549ee, []int{5}
}

func (m *ReadFeatureFlagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadFeatureFlagResponse.Unmarshal(m, b)
}
func (m *ReadFeatureFlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadFeatureFlagResponse.Marshal(b, m, deterministic)
}
func (m *ReadFeatureFlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadFeatureFlagResponse.Merge(m, src)
}
func (m *ReadFeatureFlagResponse) XXX_Size() int {
	return xxx_messageInfo_ReadFeatureFlagResponse.Size(m)
}
func (m *ReadFeatureFlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadFeatureFlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadFeatureFlagResponse proto.InternalMessageInfo

func (m *ReadFeatureFlagResponse) GetResult() *FeatureFlag {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
	proto.RegisterType((*FeatureFlag)(nil), "service.FeatureFlag")
	proto.RegisterType((*ListFeatureFlagRequest)(nil), "service.ListFeatureFlagRequest")
	proto.RegisterMapType((map[string]string)(nil), "service.ListFeatureFlagRequest.LabelsEntry")
	proto.RegisterType((*ListFeatureFlagResponse)(nil), "service.ListFeatureFlagResponse")
	proto.RegisterType((*ReadFeatureFlagRequest)(nil), "service.ReadFeatureFlagRequest")
	proto.RegisterMapType((map[string]string)(nil), "service.ReadFeatureFlagRequest.LabelsEntry")
	proto.RegisterType((*ReadFeatureFlagResponse)(nil), "service.ReadFeatureFlagResponse")
}

func init() {
	proto.RegisterFile("github.com/Infoblox-CTO/atlas.feature.flag/pkg/pb/service.proto", fileDescriptor_6544829dd69549ee)
}

var fileDescriptor_6544829dd69549ee = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x26, 0x49, 0x4d, 0x75, 0x22, 0x58, 0x86, 0x92, 0xac, 0xb1, 0xd0, 0xba, 0x57, 0xc5, 0x36,
	0x33, 0x10, 0x8b, 0xa8, 0xbd, 0x10, 0x2d, 0x6d, 0x51, 0x8a, 0x96, 0x55, 0xbc, 0x50, 0xb0, 0xcc,
	0x26, 0x27, 0xe3, 0xd8, 0xc9, 0xce, 0x74, 0x66, 0x36, 0x1a, 0xc4, 0x1b, 0x5f, 0xc1, 0xe7, 0xf0,
	0x41, 0xbc, 0xf6, 0x15, 0x7c, 0x01, 0xdf, 0x40, 0x76, 0x77, 0x52, 0xd6, 0x64, 0x8b, 0x0a, 0xde,
	0xed, 0x9c, 0xf9, 0xf6, 0xfb, 0xe6, 0x7c, 0xe7, 0x07, 0x3d, 0xe0, 0xc2, 0xbd, 0x4d, 0x63, 0x32,
	0x50, 0x63, 0xfa, 0x38, 0x19, 0xa9, 0x58, 0xaa, 0x0f, 0xbd, 0xbd, 0x17, 0xcf, 0x28, 0x73, 0x92,
	0x59, 0x32, 0x02, 0xe6, 0x52, 0x03, 0x64, 0x24, 0x19, 0xa7, 0xfa, 0x94, 0x53, 0x1d, 0x53, 0x0b,
	0x66, 0x22, 0x06, 0x40, 0xb4, 0x51, 0x4e, 0xe1, 0x65, 0x7f, 0xec, 0xde, 0xe0, 0x4a, 0x71, 0x09,
	0x34, 0x0f, 0xc7, 0xe9, 0x88, 0xc2, 0x58, 0xbb, 0x69, 0x81, 0xea, 0xae, 0xf9, 0x4b, 0xa6, 0x05,
	0x65, 0x49, 0xa2, 0x1c, 0x73, 0x42, 0x25, 0xd6, 0xdf, 0xee, 0x96, 0x1e, 0x21, 0xa7, 0x23, 0x57,
	0x70, 0x0c, 0x7a, 0x1c, 0x92, 0xde, 0x84, 0x49, 0x31, 0x64, 0x0e, 0xe8, 0xc2, 0x87, 0xff, 0x79,
	0xbb, 0x04, 0xb6, 0xef, 0x19, 0xe7, 0x60, 0xa8, 0xd2, 0x39, 0x7d, 0x85, 0xd4, 0x93, 0x92, 0x94,
	0xf0, 0xf9, 0x2a, 0x0d, 0x49, 0x91, 0x6f, 0x8f, 0x69, 0xdd, 0x73, 0x4a, 0xc9, 0x53, 0xe1, 0xe8,
	0x59, 0x0a, 0x66, 0x4a, 0x07, 0x4a, 0x4a, 0x18, 0x64, 0x14, 0x27, 0x4a, 0x83, 0x61, 0x4e, 0x19,
	0xcf, 0x15, 0x6e, 0xa1, 0x6b, 0x2f, 0xc1, 0x58, 0xa1, 0x92, 0x08, 0xac, 0x56, 0x89, 0x05, 0x1c,
	0xa0, 0xe5, 0x49, 0x11, 0x0a, 0x6a, 0x1b, 0xb5, 0xcd, 0x2b, 0xd1, 0xec, 0x18, 0xbe, 0x41, 0xad,
	0x83, 0xc2, 0xcc, 0x03, 0xc9, 0x38, 0xbe, 0x89, 0xae, 0x7a, 0x6f, 0x4f, 0x12, 0x36, 0x06, 0x8f,
	0x6e, 0xf9, 0xd8, 0x53, 0x36, 0x06, 0xbc, 0x8a, 0x2e, 0x4d, 0x98, 0x4c, 0x21, 0xa8, 0xe7, 0x77,
	0xc5, 0x01, 0xb7, 0x51, 0x53, 0x19, 0xc1, 0x45, 0x12, 0x34, 0xf2, 0xb0, 0x3f, 0x85, 0xdf, 0x6a,
	0xa8, 0x7d, 0x24, 0xac, 0x2b, 0x89, 0x44, 0x70, 0x96, 0x82, 0x75, 0x98, 0xa2, 0xe6, 0x48, 0x48,
	0x07, 0x26, 0x57, 0x69, 0xf5, 0x3b, 0x64, 0x96, 0x39, 0x61, 0x5a, 0x90, 0x83, 0xfc, 0x4e, 0x24,
	0x3c, 0xf2, 0x30, 0xbc, 0x87, 0x9a, 0x92, 0xc5, 0x20, 0x6d, 0x50, 0xdf, 0x68, 0x6c, 0xb6, 0xfa,
	0x5b, 0x64, 0x56, 0xf3, 0x6a, 0x05, 0x72, 0x94, 0xa3, 0xf7, 0x13, 0x67, 0xa6, 0x91, 0xff, 0xb5,
	0x7b, 0x0f, 0xb5, 0x4a, 0x61, 0xbc, 0x82, 0x1a, 0xa7, 0x30, 0xf5, 0x79, 0x66, 0x9f, 0xd5, 0xf9,
	0xdd, 0xaf, 0xdf, 0xad, 0x85, 0x29, 0xea, 0x2c, 0x08, 0x79, 0x83, 0x09, 0x5a, 0x36, 0x60, 0x53,
	0xe9, 0x6c, 0x50, 0xcb, 0xdf, 0xb6, 0x7a, 0xfe, 0xb6, 0x32, 0x7c, 0x06, 0xc2, 0xb7, 0xd0, 0x92,
	0x66, 0xbc, 0xd0, 0x68, 0xf5, 0xdb, 0xbf, 0x67, 0x7e, 0xcc, 0x38, 0x64, 0x4d, 0x1f, 0xe5, 0x98,
	0xf0, 0x67, 0x0d, 0xb5, 0x23, 0x60, 0xc3, 0x0a, 0x0b, 0xff, 0xa2, 0x5c, 0x3b, 0x99, 0xcb, 0x20,
	0x87, 0xd6, 0x6b, 0xad, 0xcd, 0xbb, 0x0c, 0x72, 0xf8, 0x1c, 0x7c, 0x2f, 0x45, 0x1e, 0x5b, 0xb2,
	0xba, 0x31, 0x67, 0x75, 0xf5, 0x4b, 0xfe, 0xb7, 0xd5, 0x87, 0xa8, 0xb3, 0x20, 0xe4, 0xad, 0xde,
	0x46, 0xcd, 0xc2, 0x45, 0xdf, 0x36, 0xd5, 0x4e, 0x7b, 0x4c, 0xff, 0x6b, 0x1d, 0xad, 0x3c, 0xcc,
	0x66, 0xa8, 0xdc, 0xe5, 0xc7, 0x08, 0x1d, 0x82, 0xf3, 0x43, 0x82, 0xdb, 0xa4, 0xd8, 0x02, 0x64,
	0xb6, 0x22, 0xc8, 0x7e, 0xb6, 0x22, 0xba, 0xc1, 0x39, 0xf1, 0xdc, 0x38, 0x85, 0x2b, 0x9f, 0xbf,
	0xff, 0xf8, 0x52, 0x47, 0xf8, 0x32, 0xf5, 0x63, 0x84, 0x5f, 0xa3, 0xa5, 0xac, 0x35, 0xf0, 0xfa,
	0x1f, 0x5a, 0xb2, 0xbb, 0x71, 0x31, 0x60, 0x81, 0xdc, 0x97, 0x11, 0xbf, 0x43, 0x4b, 0x99, 0x19,
	0x25, 0xf2, 0xea, 0x22, 0x94, 0xc8, 0x2f, 0x30, 0x2f, 0x5c, 0xcf, 0xc9, 0xaf, 0xe3, 0xce, 0x8c,
	0x9c, 0x7e, 0x2c, 0x37, 0xd0, 0xa7, 0x47, 0x77, 0x5e, 0xed, 0xfc, 0xf3, 0xea, 0xdd, 0xd5, 0x71,
	0xdc, 0xcc, 0xcd, 0xbb, 0xfd, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x68, 0x78, 0x15, 0xca, 0xb9, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AtlasFeatureFlagClient is the client API for AtlasFeatureFlag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AtlasFeatureFlagClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	List(ctx context.Context, in *ListFeatureFlagRequest, opts ...grpc.CallOption) (*ListFeatureFlagResponse, error)
	Read(ctx context.Context, in *ReadFeatureFlagRequest, opts ...grpc.CallOption) (*ReadFeatureFlagResponse, error)
}

type atlasFeatureFlagClient struct {
	cc *grpc.ClientConn
}

func NewAtlasFeatureFlagClient(cc *grpc.ClientConn) AtlasFeatureFlagClient {
	return &atlasFeatureFlagClient{cc}
}

func (c *atlasFeatureFlagClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.AtlasFeatureFlag/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atlasFeatureFlagClient) List(ctx context.Context, in *ListFeatureFlagRequest, opts ...grpc.CallOption) (*ListFeatureFlagResponse, error) {
	out := new(ListFeatureFlagResponse)
	err := c.cc.Invoke(ctx, "/service.AtlasFeatureFlag/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atlasFeatureFlagClient) Read(ctx context.Context, in *ReadFeatureFlagRequest, opts ...grpc.CallOption) (*ReadFeatureFlagResponse, error) {
	out := new(ReadFeatureFlagResponse)
	err := c.cc.Invoke(ctx, "/service.AtlasFeatureFlag/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtlasFeatureFlagServer is the server API for AtlasFeatureFlag service.
type AtlasFeatureFlagServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
	List(context.Context, *ListFeatureFlagRequest) (*ListFeatureFlagResponse, error)
	Read(context.Context, *ReadFeatureFlagRequest) (*ReadFeatureFlagResponse, error)
}

func RegisterAtlasFeatureFlagServer(s *grpc.Server, srv AtlasFeatureFlagServer) {
	s.RegisterService(&_AtlasFeatureFlag_serviceDesc, srv)
}

func _AtlasFeatureFlag_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasFeatureFlagServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AtlasFeatureFlag/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasFeatureFlagServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtlasFeatureFlag_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasFeatureFlagServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AtlasFeatureFlag/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasFeatureFlagServer).List(ctx, req.(*ListFeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtlasFeatureFlag_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasFeatureFlagServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AtlasFeatureFlag/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasFeatureFlagServer).Read(ctx, req.(*ReadFeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AtlasFeatureFlag_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.AtlasFeatureFlag",
	HandlerType: (*AtlasFeatureFlagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _AtlasFeatureFlag_GetVersion_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AtlasFeatureFlag_List_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _AtlasFeatureFlag_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/Infoblox-CTO/atlas.feature.flag/pkg/pb/service.proto",
}
